sudo: required
services:
  - docker

before_install:
  - docker build -t parmenakis/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true parmenakis/docker-react npm run test -- --coverage

#after_success:
#  - docker build -t parmenakis/docker-react .
#  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin